FROM postgres:12-alpine

ARG POSTGRES_DB
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD

ENV POSTGRES_DB $POSTGRES_DB \
    POSTGRES_USER $POSTGRES_USER \
    POSTGRES_PASSWORD $POSTGRES_PASSWORD

WORKDIR /docker-entrypoint-initdb.d

RUN apk --no-cache update
